#!/usr/bin/python3
#!/usr/bin/env python

import py_compile
import os

# Get the name of the Python file from the environment variable
py_file = os.environ.get('PYFILE')

if py_file is None:
    print('Error: PYFILE environment variable not set')
    exit(1)

# Compile the Python file
py_compile.compile(py_file, cfile=py_file+'c')

print('Compilation completed successfully')
